set_velx(200), set_accx(200)
# x 속도   x 가속도
set_velj(30), set_accj(30)
# j 속도     j 가속도


   #   x        y             z          A         B       C
posx(-6.06, 367.83, 254.83, 92.26, -179.97, 92.25)
#Ctrl + W    현재 x 좌표

posj(89.98, 0, 90.03, 0, 90.01, 89.98)
#Ctrl + Q    현재 j 좌표

movej(posj(86.79, 1.22, 86.87, -0.6, 91.21, 92.41))
# j 
movel(posx(18.16, 379.67, 267.2, 45.81, 179.08, 51.45))
# l

movel(trans())