w = "5 0 0 W S S 0 1 0 6 % D W 0 0 0 0 0 0 0 4".split()
r = "5 0 0 R S S 0 1 0 6 % D W 0 0 0 4".split()
w[0],r[0] = [5]*2
w[20],r[16] = [4]*2
for i in range(1, 20):
    w[i] = ord(w[i])
    if i < 16: r[i] = ord(r[i])
def write(ad, val):
    ser = serial_open(port = "COM")
    w[14] = ord(str(ad//10))
    w[15] = ord(str(ad%10))
    w[18] = ord(str(0)) if val < 16 else ord(hex(val)[2])
    w[19] = ord(hex(val)[2]) if val < 16 else ord(hex(val)[3])
    ser.write(bytearray(w))
    serial_close(ser)
    wait(0.02)
    
def read(ad):
    ser = serial_open(port ="COM")
    r[14] = ord(str(ad//10))
    r[15] = ord(str(ad%10))
    ser.write(bytearray(r))
    wait(0.02)
    _sum = int(ser.read(ser.inWaiting()).decode()[10:14], 16)
    serial_close(ser)
    return _sum
    
write(91,1)